---
title: "ai_with_noclosure"
author: "Sara Orofino"
date: "4/3/2020"
output: html_document
---


I want to replicate the graphs used in faculty reviews for assessment intervals but instead use the new combined data where instead of closing the fishery if it is over the limit, catch is reduced by 95%.  

## Packages/Data 

```{r packages-data, warning=FALSE, message=FALSE}
library(tidyverse)
library(here)

ai_c <- read_csv(file=file.path(here(), "/analysis/no_closure/all_data/noclose_all_c.csv"))
```


## Wrangle
```{r wrangle}
##Wrangling with the combined data set:
ai_intervals <- c(20,15,10,5,1) #new intervals in correct order

ai_c[is.na(ai_c)] <- "misc" #turn status NA into misc

# Calculate proportions for graphing:
ai_props_c <- ai_c %>% 
  mutate(assess_int = factor(assess, levels = ai_intervals)) %>%
  group_by(assess_int) %>%
  count(status) %>% 
  spread(key = "status", value = "n") %>% 
  mutate(simulations = sum(over + good + misc)) %>% 
  mutate(prop_good = good / simulations)
```

## Graph Constant FMSY:
```{r graph-constant}
ai_c_graph <- ggplot(ai_props_c, aes(x = assess_int, y = prop_good)) +
  geom_col(alpha = 0.7, fill = "#079EDF") + 
  theme_light()+
  coord_cartesian( ylim=c(0,1), expand = FALSE ) +
  labs(title = "Assessment Intervals", x = "Frequency of Assessment (Years)", y = "Proportion Healthy")+
  theme(axis.text.x=element_text(size=15), axis.text.y=element_text(size=15), plot.title = element_text(hjust = 0.5, face = "bold", size = 20), axis.title.x = element_text(face = "bold", size = 15), axis.title.y = element_text(face = "bold", size = 15), legend.title.align=0.5, panel.background = element_rect(fill = "transparent",colour = NA), plot.background = element_rect(fill = "transparent",colour = NA), legend.title=element_text(size=15), 
    legend.text=element_text(size=12),legend.key = element_rect(fill = "transparent", colour = "transparent"), legend.background = element_blank(),
    legend.box.background = element_blank()) 

ai_c_graph

# ggsave(ai_c_graph, filename = "ai_c_noclose.png",  bg = "transparent",
#       width = 6, height = 4)
```

## New Updating Data (no closure)  

```{r read-updating, warning=FALSE, message=FALSE}
ai_u <- read_csv(file=file.path(here(), "/analysis/no_closure/all_data/noclose_all_u.csv"))
```

## Wrangle Updating
```{r wrangle}
##Wrangling with the combined data set:
ai_intervals <- c(20,15,10,5,1) #new intervals in correct order

ai_u[is.na(ai_u)] <- "misc" #turn status NA into misc

# Calculate proportions for graphing:
ai_props_u <- ai_u %>% 
  mutate(assess_int = factor(assess, levels = ai_intervals)) %>%
  group_by(assess_int) %>%
  count(status) %>% 
  spread(key = "status", value = "n") %>% 
  mutate(simulations = sum(over + good + misc)) %>% 
  mutate(prop_good = good / simulations)
```

## Create Graphing Data - both

```{r wrangle-graph-data, include=FALSE}

##Create the all graph data frame - start with constant and add updating then merge:
graph_c <- data.frame(assessment_interval = ai_props_c$assess_int, productivity = rep("constant", 5),
                      prop_good = ai_props_c$prop_good)
graph_u <- data.frame(assessment_interval = ai_props_u$assess_int, productivity = rep("updating", 5),
                      prop_good = ai_props_u$prop_good)
graph_both <- rbind(graph_c, graph_u)

```


## Graph Constant vs. Updating
```{r graph-both}
ai_both <- ggplot(graph_both, aes(x = assessment_interval, y = prop_good, fill = productivity)) +
  geom_col(position = "dodge", alpha = 0.7) + 
  scale_fill_manual(values = c("#079EDF", "#BC6435"), name = "Climate Response", labels = c("None", "Perfect"))+
  theme_light()+
  coord_cartesian( ylim=c(0,1), expand = FALSE ) +
  labs(title = "Assessment Intervals", x = "Frequency of Assessment (Years)", y = "Proportion Healthy")+
  theme(axis.text.x=element_text(size=15), axis.text.y=element_text(size=15), plot.title = element_text(hjust = 0.5, face = "bold", size = 20), axis.title.x = element_text(face = "bold", size = 15), axis.title.y = element_text(face = "bold", size = 15), legend.title.align=0.5, panel.background = element_rect(fill = "transparent",colour = NA), plot.background = element_rect(fill = "transparent",colour = NA), legend.title=element_text(size=15), 
    legend.text=element_text(size=12),legend.key = element_rect(fill = "transparent", colour = "transparent"), legend.background = element_blank(),
    legend.box.background = element_blank()) 

ai_both

# ggsave(ai_both, filename = "ai_both_noclose.png",  bg = "transparent",
#       width = 6, height = 4)
```