---
title: "combine_runs"
author: "Sara Orofino"
date: "4/2/2020"
output: html_document
---

Combine the year 100 biomasses from the low, mid, and high error runs at the different assessment levels for analysis.  

## Packages
```{r packages}
library(tidyverse)
library(here)
```

## Read Data

Read in the datasets:  
```{r read-in, warning=FALSE, message=FALSE}
#Assessment interval 1 year:
low_1 <- read_csv(file=file.path(here(),"/Results/no_closure/lowerror/lowerr_1_95.csv"))
mid_1<- read_csv(file=file.path(here(),"/Results/no_closure/miderror/miderr_1_95.csv"))
high_1 <- read_csv(file=file.path(here(),"/Results/no_closure/higherror/higherr_1_95.csv"))

#Assessment interval 5 year:
low_5 <- read_csv(file=file.path(here(),"/Results/no_closure/lowerror/lowerr_5_95.csv"))
mid_5 <- read_csv(file=file.path(here(),"/Results/no_closure/miderror/miderr_5_95.csv"))
high_5 <- read_csv(file=file.path(here(),"/Results/no_closure/higherror/higherr_5_95.csv"))

#Assessment interval 10 years:
low_10 <- read_csv(file=file.path(here(),"/Results/no_closure/lowerror/lowerr_10_95.csv"))
mid_10 <- read_csv(file=file.path(here(),"/Results/no_closure/miderror/miderr_10_95.csv"))
high_10 <- read_csv(file=file.path(here(),"/Results/no_closure/higherror/higherr_10_95.csv"))

#Assessment interval 15 years:
low_15 <- read_csv(file=file.path(here(),"/Results/no_closure/lowerror/lowerr_15_95.csv"))
mid_15 <- read_csv(file=file.path(here(),"/Results/no_closure/miderror/miderr_15_95.csv"))
high_15 <- read_csv(file=file.path(here(),"/Results/no_closure/higherror/higherr_15_95.csv"))

#Assessment interval 20 years:
low_20 <- read_csv(file=file.path(here(),"/Results/no_closure/lowerror/lowerr_20_95.csv"))
mid_20 <- read_csv(file=file.path(here(),"/Results/no_closure/miderror/miderr_20_95.csv"))
high_20 <- read_csv(file=file.path(here(),"/Results/no_closure/higherror/higherr_20_95.csv"))

```




