---
title: "objective_1_graph"
author: "Chase Brewster"
date: "1/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

```{r}
msy <- read_csv(file=file.path(here(), "/Tests/perfect_management/csv_results/perfect_noclim.csv"))
noclim <- read_csv(file=file.path(here(),"/Presentation/objective_1/noclimate.csv"))
noclim_perf <- read_csv(file=file.path(here(),"/Presentation/objective_1/noclimate_perfect.csv"))
perfect <- read_csv(file=file.path(here(),"/Presentation/objective_1/perfect_climate.csv"))
realistic <- read_csv(file=file.path(here(),"/Presentation/objective_1/realistic_climate.csv"))

```

```{r}

msy_1 <- msy %>% 
  mutate(ID = id) %>% 
  mutate(run = "msy") %>% 
  filter(r_0 == 0.4) 
  

noclim_1 <- noclim %>%
  filter(r == 0.4) %>% 
  filter(hcr == 0.7) %>% 
  mutate(run = "noclim") %>% 
  mutate(ID = id)

noclim_perf_1 <- noclim_perf %>%
  filter(r == 0.4) %>% 
  filter(hcr == 0.7) %>% 
  mutate(run = "noclim_perf") %>% 
  mutate(ID = id + 10)

perfect_1 <- perfect %>% 
  filter(r_0 == 0.4) %>% 
  filter(hcr == 0.7) %>% 
  filter(r_s == -0.00767) %>% 
  mutate(run = "perfect") %>% 
  mutate(ID = id + 100)

realistic_1 <- realistic %>%
  filter(r_0 == 0.4) %>% 
  filter(hcr == 0.7) %>% 
  filter(r_s == -0.00767) %>% 
  mutate(run = "realistic") %>% 
  mutate(ID = id + 1000)

all_results <- rbind(noclim_1, perfect_1, realistic_1, noclim_perf_1) %>% 
  bind_rows(msy_1) %>% 
  group_by(ID) %>% 
  filter(b_0 == 1500)

select_results <- rbind(noclim_1, realistic_1) %>% 
  bind_rows(msy_1) %>% 
  group_by(ID) %>% 
  filter(b_0 == 1500) %>% 
  filter(run != "msy")

```

```{r}

obj_1_graph <- ggplot(select_results, aes(x = year, y = b, group = ID)) +
  geom_line(aes(color = run), size = 1.25) +
  scale_color_manual(values = c("#079EDF", "#B8CE55"), name = "Scenario", labels = c("No Climate Change", "Climate Change"))+
  theme_light() +
  coord_cartesian( ylim=c(0,6000), expand = FALSE ) +
  labs(title = "FISHE Mangement", x = "Year", y = "Biomass")+
  theme(legend.key = element_rect(fill = "transparent", colour = "transparent"), axis.text.x=element_text(size=15), axis.text.y=element_text(size=15), plot.title = element_text(hjust = 0.5, face = "bold", size = 15), axis.title.x = element_text(face = "bold", size = 15), axis.title.y = element_text(face = "bold", size = 15), legend.title.align=0.5, panel.background = element_rect(fill = "transparent",colour = NA), plot.background = element_rect(fill = "transparent",colour = NA), legend.title=element_text(size=15), 
    legend.text=element_text(size=12), legend.background = element_blank(),
    legend.box.background = element_blank())

obj_1_graph
ggsave(obj_1_graph, filename = "obj_1.png",  bg = "transparent")
```

A second graph for the report that compares the yearly implementation of FISHE with and without climate:
```{r}
#Copy the noclim perfect and perfect with clim from above:
noclim_perf_1 <- noclim_perf %>%
  filter(r == 0.4) %>% 
  filter(hcr == 0.7) %>% 
  mutate(run = "noclim_perf") %>% 
  mutate(ID = id + 10)

perfect_1 <- perfect %>% 
  filter(r_0 == 0.4) %>% 
  filter(hcr == 0.7) %>% 
  filter(r_s == -0.00767) %>% 
  mutate(run = "perfect") %>% 
  mutate(ID = id + 100)

graph_df <- rbind(noclim_perf_1, perfect_1) %>% 
  group_by(ID) %>% 
  filter(b_0 == 1500)

##Graph it:
obj_1_graph2 <- ggplot(graph_df, aes(x = year, y = b, group = ID)) +
  geom_line(aes(color = run), size = 1.25) +
  scale_color_manual(values = c("#079EDF", "#B8CE55"), name = "Scenario", labels = c("No Climate Change", "Climate Change"))+
  theme_light() +
  coord_cartesian( ylim=c(0,6000), expand = FALSE ) +
  labs(title = "FISHE Mangement", x = "Year", y = "Biomass")+
  theme(legend.key = element_rect(fill = "transparent", colour = "transparent"), axis.text.x=element_text(size=15), axis.text.y=element_text(size=15), plot.title = element_text(hjust = 0.5, face = "bold", size = 15), axis.title.x = element_text(face = "bold", size = 15), axis.title.y = element_text(face = "bold", size = 15), legend.title.align=0.5, panel.background = element_rect(fill = "transparent",colour = NA), plot.background = element_rect(fill = "transparent",colour = NA), legend.title=element_text(size=15), 
    legend.text=element_text(size=12), legend.background = element_blank(),
    legend.box.background = element_blank())

obj_1_graph2
ggsave(obj_1_graph2, filename = "obj_1_ideal.png",  bg = "transparent")
```

