---
title: "Graph for Presentation, Objective 1"
author: "Chase Brewster"
date: "1/21/2020"
output: html_document
---

#{.tabset}
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(purrr)
```


```{r model-setup}

#create an interval vector for times that we do want to do the assessment:
assess_int <- seq(10,100,10)

#Write a "not contained in" function"
`%not_in%` <- purrr::negate(`%in%`)
```
 
```{r model-setup}

#create an interval vector for times that we do want to do the assessment:
assess_int <- seq(1,100,1)

#Write a "not contained in" function"
`%not_in%` <- purrr::negate(`%in%`)
``` 


```{r model-constant}

#Baseline model with error around the f_ratio (f/fmsy) and repetition of the assessment process every 10 years for the duration of the simulation:

sim_constant <- function(b, r, r_s, error, p, k, years, hcr){ #hcr term is added into the model to run a cross list of a number of different hcr possibilities
  
  results <- data.frame(
    b = rep(NA, years), c = rep(NA, years), 
    year = 1:years, r = rep(NA, years), f = rep(NA, years),
    f_msy = rep(NA, years), f_ratio = rep(NA, years), f_ratio_p = rep(NA, years), f_ratio_err = rep(NA, years)) #Setup the results dataframe 
  
  #Set the initial result for the outputs in year 1
  results$b[1] = b
  results$r[1] = r
  f_int = (results$r[1] / p) * (1 - ((results$b[1] / k) ^ p)) #initial f assuming catch = surplus
  
  
  fmsy <-function(r,p){r * (1 / (1+p))} #set up the function to calculate Fmsy based on growth (r) and shape parameter (p)
  r_calc1 <- results$r[1]
  results$f_msy[1] <- fmsy(r=r_calc1, p=p) #calculate fmsy in year 1 based on historical parameters
  results$f_ratio[1] = f_int/results$f_msy[1] #calculate the actual f_ratio from initial fishing pressure (this is basically f in time t-1) and fmsy
  results$f_ratio_p[1] = results$f_ratio[1] #this is the perceived f ratio by the fisheries managers - with climate change, this perceived ratio will not adjust fmsy as climate shifts productivity

  #Log transform the mean (m) and stdev (s):
  mu_1 <- log(results$f_ratio_p[1]) 
  cv <- error
  sd_1 <- sqrt(log(cv^2+1))
  
  #Draw the f_ratio_err:
  results$f_ratio_err[1] <- rlnorm(1, meanlog = mu_1, sdlog = sd_1)

  
  #Decide how to change f based on the f ratio estimate with error:
  if(results$f_ratio_err[1] >= 2){
       results$f[1] = hcr*f_int #Close the fishery
   } 
    if(results$f_ratio_err[1] > 1.1 & results$f_ratio_err[1] < 2){
       results$f[1] = hcr*f_int #Reduce by hcr
   }  
    if(results$f_ratio_err[1] > 1 & results$f_ratio_err[1] < 1.1){
       results$f[1] = f_int  #f stays the same in as last year
   }
    if(results$f_ratio_err[1] < 1){
       results$f[1] = 1.05*f_int #f increases by 5% from last year
   } 
  
  #Calculate catch in year one based on the new f:
  results$c[1] = results$f[1] * results$b[1] 
  
  ## Loop the model over the specified number of years
  # Repeat on 10 year intervals - make the HCR decision based on the previous years data and apply the f to the current assessment year, this f remains constant until next assessment
  for (t in 2:years) {
    if(results$year[t] %in% assess_int){
    
    results$r[t] = results$r[t-1] + (r_s*results$r[t-1])
    
    ##HCR decision will change how f is calculated - this step must come before calculating c 
    # Calculate fmsy in time t from current r 
    r_calc2 <- results$r[t]
    results$f_msy[t] <- fmsy(r=r_calc2, p=p)
    results$f_ratio[t] <- results$f[t-1]/results$f_msy[t-1] #the ratio of f/fmsy at the beginning of the year is based on last years f and fmsy
    results$f_ratio_p[t] <- results$f[t-1]/results$f_msy[1] #the perceived f ratio is based on the original fmsy from the first assessment

    #Transform to new mean (mu)
    if(results$f_ratio_p[t] != 0){
       #Assign values to normal dist mean (m):
       mu_2 <- log(results$f_ratio_p[t])
       #Draw the f_ratio_err
       results$f_ratio_err[t] <- rlnorm(1, meanlog = mu_2, sdlog = sd_1)
    }
    if(results$f_ratio_p[t] == 0){
       results$f_ratio_err[t] = 0
    }
    
    #Decisions for f this year based on the ratio with error in the previous year 
    if(results$f_ratio_err[t] >= 2){
       results$f[t] = 0 
   } 
    if(results$f_ratio_err[t] > 1.1 & results$f_ratio_err[t] < 2){
       results$f[t] = hcr*results$f[t-1] #Reduce by hcr - same thing as keeping (hcr%) of previous fishing mortality
   }  
    if(results$f_ratio_err[t] > 1 & results$f_ratio_err[t] < 1.1){
       results$f[t] = results$f[t-1]  #f stays the same in as last year
   }
    if(results$f_ratio_err[t] < 1){
       results$f[t] = 1.05*results$f[t-1] #f increases by 5% from last year
   } 
    
    
    #Calculate remaining results - pay attention to the order!
    results$b[t] = results$b[t-1] + (results$r[t-1] / p)*results$b[t-1]*(1 - ((results$b[t-1]/k) ^ p))-results$c[t-1]
    results$c[t] = results$f[t] * results$b[t]
   } 

  if(results$year[t] %not_in% assess_int){
    results$r[t] = results$r[t-1] + (r_s*results$r[t-1])
    results$b[t] = results$b[t-1] + (results$r[t-1] / p)*results$b[t-1]*(1 - ((results$b[t-1]/k) ^ p))-results$c[t-1]
    results$f[t] = results$f[t-1]
    results$c[t] = results$f[t] * results$b[t]
    r_calc3 <- results$r[t]
    results$f_msy[t] = fmsy(r=r_calc3, p=p) #Fmsy needs to update every year to capture productivity changes
    results$f_ratio_err[t] = results$f_ratio_err[t-1]
    results$f_ratio[t] = results$f[t-1]/results$f_msy[t-1]
    results$f_ratio_p[t] = results$f_ratio_p[t-1]
    
  }
}
  return(results)
}


```
 

```{r model - updating}

#Baseline model with error around the f_ratio (f/fmsy) and repetition of the assessment process every 10 years for the duration of the simulation:

sim_updating <- function(b, r, r_s, error, p, k, years, hcr){ #hcr term is added into the model to run a cross list of a number of different hcr possibilities
  
  results <- data.frame(
    b = rep(NA, years), c = rep(NA, years), 
    year = 1:years, r = rep(NA, years), f = rep(NA, years),
    f_msy = rep(NA, years), f_ratio = rep(NA, years), f_ratio_p = rep(NA, years), f_ratio_err = rep(NA, years)) #Setup the results dataframe 
  
  #Set the initial result for the outputs in year 1
  results$b[1] = b
  results$r[1] = r
  f_int = (results$r[1] / p) * (1 - ((results$b[1] / k) ^ p)) #initial f assuming catch = surplus
  
  
  fmsy <-function(r,p){r * (1 / (1+p))} #set up the function to calculate Fmsy based on growth (r) and shape parameter (p)
  r_calc1 <- results$r[1]
  results$f_msy[1] <- fmsy(r=r_calc1, p=p) #calculate fmsy in year 1 based on historical parameters
  results$f_ratio[1] = f_int/results$f_msy[1] #calculate the actual f_ratio from initial fishing pressure (this is basically f in time t-1) and fmsy
  results$f_ratio_p[1] = results$f_ratio[1] #this is the perceived f ratio by the fisheries managers - with climate change, this perceived ratio will adjust fmsy as climate shifts productivity

  #Log transform the mean (m) and stdev (s):
  mu_1 <- log(results$f_ratio_p[1]) 
  cv <- error
  sd_1 <- sqrt(log(cv^2+1))
  
  #Draw the f_ratio_err:
  results$f_ratio_err[1] <- rlnorm(1, meanlog = mu_1, sdlog = sd_1)

  
  #Decide how to change f based on the f ratio estimate with error:
  if(results$f_ratio_err[1] >= 2){
       results$f[1] = hcr*f_int #Close the fishery
   } 
    if(results$f_ratio_err[1] > 1.1 & results$f_ratio_err[1] < 2){
       results$f[1] = hcr*f_int #Reduce by hcr
   }  
    if(results$f_ratio_err[1] > 1 & results$f_ratio_err[1] < 1.1){
       results$f[1] = f_int  #f stays the same in as last year
   }
    if(results$f_ratio_err[1] < 1){
       results$f[1] = 1.05*f_int #f increases by 5% from last year
   } 
  
  #Calculate catch in year one based on the new f:
  results$c[1] = results$f[1] * results$b[1] 
  
  ## Loop the model over the specified number of years
  # Repeat on 10 year intervals - make the HCR decision based on the previous years data and apply the f to the current assessment year, this f remains constant until next assessment
  for (t in 2:years) {
    if(results$year[t] %in% assess_int){
    
    results$r[t] = results$r[t-1] + (r_s*results$r[t-1])
    
    ##HCR decision will change how f is calculated - this step must come before calculating c 
    # Calculate fmsy in time t from current r 
    r_calc2 <- results$r[t]
    results$f_msy[t] <- fmsy(r=r_calc2, p=p)
    results$f_ratio[t] <- results$f[t-1]/results$f_msy[t-1] #the ratio of f/fmsy at the beginning of the year is based on last years f and fmsy
    results$f_ratio_p[t] <- results$f[t-1]/results$f_msy[t-1] #the perceived f ratio is based on the climate adjusted fmsy

    #Transform to new mean (mu) and stdev (stdev)
    if(results$f_ratio_p[t] != 0){
       #Assign values to normal dist mean (m):
       mu_2 <- log(results$f_ratio_p[t])
       #Draw the f_ratio_err
       results$f_ratio_err[t] <- rlnorm(1, meanlog = mu_2, sdlog = sd_1)
    }
    if(results$f_ratio_p[t] == 0){
       results$f_ratio_err[t] = 0
    }
    
    #Decisions for f this year based on the ratio with error in the previous year 
    if(results$f_ratio_err[t] >= 2){
       results$f[t] = 0 
   } 
    if(results$f_ratio_err[t] > 1.1 & results$f_ratio_err[t] < 2){
       results$f[t] = hcr*results$f[t-1] #Reduce by 10% - same thing as keeping 90% of previous fishing mortality
   }  
    if(results$f_ratio_err[t] > 1 & results$f_ratio_err[t] < 1.1){
       results$f[t] = results$f[t-1]  #f stays the same in as last year
   }
    if(results$f_ratio_err[t] < 1){
       results$f[t] = 1.05*results$f[t-1] #f increases by 5% from last year
   } 
    
    
    #Calculate remaining results - pay attention to the order!
    results$b[t] = results$b[t-1] + (results$r[t-1] / p)*results$b[t-1]*(1 - ((results$b[t-1]/k) ^ p))-results$c[t-1]
    results$c[t] = results$f[t] * results$b[t]
   } 

  if(results$year[t] %not_in% assess_int){
    results$r[t] = results$r[t-1] + (r_s*results$r[t-1])
    results$b[t] = results$b[t-1] + (results$r[t-1] / p)*results$b[t-1]*(1 - ((results$b[t-1]/k) ^ p))-results$c[t-1]
    results$f[t] = results$f[t-1]
    results$c[t] = results$f[t] * results$b[t]
    r_calc3 <- results$r[t]
    results$f_msy[t] = fmsy(r=r_calc3, p=p) #Fmsy needs to update every year to capture productivity changes
    results$f_ratio_err[t] = results$f_ratio_err[t-1]
    results$f_ratio[t] = results$f[t-1]/results$f_msy[t-1]
    results$f_ratio_p[t] = results$f_ratio_p[t-1]
    
  }
}
  return(results)
}


```


```{r experiment-inputs}

#Design experiments
list_update <- list(
  b = c(1500, 4000),
  r = seq(0.1, .8, .1),
  r_s = seq(-0.01767, 0.01623, 0.002),
  error = 0.1,
  p = 0.2,
  k = 10000,
  years = 100,
  hcr = seq(0.90, 0.60, -0.05)
)

input_update <- list_update %>%
  cross()


```


```{r run}

results = list()

#Run the model over the input lists:

for(i in 1:1904){
  results[[i]] <- sim_constant(b=input_update[[i]]$b, r=input_update[[i]]$r,
                             r_s=input_update[[i]]$r_s, p=input_update[[i]]$p,
                             k=input_update[[i]]$k,years=input_update[[i]]$years, 
                             error = input_update[[i]]$error, hcr = input_update[[i]]$hcr)
}

```

```{r save-csv}

#Create the list of column names:

col_names <- c("b", "c", "year", "r", "f", "f_msy", "f_ratio", "f_ratio_p", "f_ratio_err", "id", "r_0", "error", "r_s", "hcr", "b_0")

#Create a new list with ids
results_id <- list()

#Loop to add ids to each experiment in the list - make sure the 1:xxx matches the number of lists in the results
for(i in 1:1904){
  dat <- as.data.frame(matrix(unlist(results[i]), ncol = 9))
  dat$id <- i
  dat$r_0 <- rep(input_update[[i]]$r, 100)
  dat$err <- rep(input_update[[i]]$error, 100)
  dat$r_s <- rep(input_update[[i]]$r_s, 100)
  dat$hcr <- rep(input_update[[i]]$hcr, 100)
  dat$b_0 <- rep(input_update[[i]]$b, 100)
  results_id[[i]] <- dat
}
#Bind all the experiments together
results_update <- bind_rows(results_id)

#Update the column names:
colnames(results_update) <- col_names

#Write as CSV:
library(here)
write.csv(results_update, file=file.path(here(),"/Presentation/objective_1/realistic_climate.csv"),
            row.names = FALSE)

```

  