---
title: "objective1_graph"
author: "Sara Orofino"
date: "4/7/2020"
output: html_document
---

Make a bar graph that compares healthy fisheries when using FISHE with no climate and then including climate change  

## Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

## Data
```{r data, message = FALSE, warning = FALSE}

noclim <- read_csv(file=file.path(here(),"/Presentation/objective_1/noclimate.csv"))
realistic <- read_csv(file=file.path(here(),"/Presentation/objective_1/realistic_climate.csv"))

```

## Wrangle Data:
Use 30% HCR  
```{r wrangle}
## No climate change data:
noclim_100 <- noclim %>% 
  filter(year == 100) %>% 
  filter(hcr == 0.85) %>% 
  mutate(status = ifelse(f_ratio == 0, "closed", ifelse(b <= 1000, "over", "good"))) %>% 
  mutate(growth = ifelse(r_0 <= .3, "slow", ifelse(r_0 > .3 & r_0 <= .5, "medium", "fast")))

noclim_count <- noclim_100 %>% 
  group_by(hcr) %>% 
  count(status) %>% 
  spread(key = "status", value = "n") %>% 
  mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>% 
  mutate(simulations = sum(good + closed)) %>% 
  mutate(prop_good = good / simulations)

## Climate Change data:  
clim_100 <- realistic %>% 
  filter(year == 100) %>% 
  filter(hcr == 0.85) %>% 
  filter(r_s < 0) %>%
  mutate(status = ifelse(f_ratio == 0, "closed", ifelse(b <= 1000, "over", "good"))) %>% 
  mutate(growth = ifelse(r_0 <= .3, "slow", ifelse(r_0 > .3 & r_0 <= .5, "medium", "fast")))

clim_100[is.na(clim_100)] <- "misc" #turn status NA into misc

clim_count <- clim_100 %>% 
  group_by(hcr) %>% 
  count(status) %>% 
  spread(key = "status", value = "n") %>% 
  mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>% 
  mutate(simulations = sum(good + over + closed)) %>% 
  mutate(prop_good = good / simulations) 

```

## Graphing Data:
```{r graph-data}
##Create graph data:
graph_noclim <- data.frame(climate = "No Climate Change", prop_good = noclim_count$prop_good)
graph_clim <- data.frame(climate = "Climate Change", prop_good = clim_count$prop_good)
graph_both <- rbind(graph_noclim, graph_clim)
```


## Graph
```{r graph}
compare <- ggplot(graph_both, aes(x = climate, y = prop_good)) +
  geom_col(alpha = 0.5, fill = "#BC6435", width = .5) + 
  theme_light()+
  coord_cartesian( ylim=c(0.05 ,1)) +
  labs(title = "FISHE Climate Comparison", x = "Climate Inclusion", y = "Proportion Healthy")+
  theme(axis.text.x=element_text(size=15), axis.text.y=element_text(size=15), plot.title = element_text(hjust = 0.5, face = "bold", size = 20), axis.title.x = element_text(face = "bold", size = 15), axis.title.y = element_text(face = "bold", size = 15), legend.title.align=0.5, panel.background = element_rect(fill = "transparent",colour = NA), plot.background = element_rect(fill = "transparent",colour = NA), legend.title=element_text(size=15), 
    legend.text=element_text(size=12),legend.key = element_rect(fill = "transparent", colour = "transparent"), legend.background = element_blank(),
    legend.box.background = element_blank(),
    panel.grid.major.x = element_blank()) 

compare
# ggsave(compare, filename = "compare.png",  bg = "transparent",
# width = 6, height = 4)

```


