---
title: "ai_lowerror_analysis_graph"
author: "Chase"
date: "1/22/2020"
output: html_document
---

#{.tabset}
```{r}
library(tidyverse)
library(here)
```
Read in constant fmsy data:  
```{r setup, include=FALSE, message=FALSE, warning = FALSE}

rep_0 <- read_csv(file=file.path(here(), "/Presentation/objective_2/ai/ai_0rep_lowerror.csv"))
rep_1 <- read_csv(file=file.path(here(), "/Presentation/objective_2/ai/ai_rep1_constant.csv"))
rep_5 <- read_csv(file=file.path(here(), "/Presentation/objective_2/ai/ai_5rep_lowerror.csv"))
rep_10 <- read_csv(file=file.path(here(), "/Presentation/objective_2/ai/ai_10rep_lowerror.csv"))
rep_15 <- read_csv(file=file.path(here(), "/Presentation/objective_2/ai/ai_15rep_lowerror.csv"))
rep_20 <- read_csv(file=file.path(here(), "/Presentation/objective_2/ai/ai_20rep_lowerror.csv"))

```

##Constant Fmsy:  
Constant fmsy wrangling:  
```{r constant-ai-wrangle, include=FALSE}

rep0_1 <- rep_0 %>% 
  mutate(closed = ifelse(f_ratio >= 2, "closed", "no")) %>% #need to add a way to track closed otherwise it will only show as overfished
  filter(year == 100) %>% 
  mutate(status = ifelse(closed == "closed", "closed", ifelse(b <= 1500, "over", "good"))) %>% 
  mutate(growth = ifelse(r_0 <= .3, "slow", ifelse(r_0 > .3 & r_0 <= .5, "medium", "fast"))) %>% 
  mutate(int = "Never") %>% 
  select(-closed)

rep1_1 <- rep_1 %>%
  filter(year == 100) %>% 
  mutate(status = ifelse(f_ratio == 0, "closed", ifelse(b <= 1500, "over", "good"))) %>% 
  mutate(growth = ifelse(r_0 <= .3, "slow", ifelse(r_0 > .3 & r_0 <= .5, "medium", "fast"))) %>% 
  mutate(int = 1)   
  
rep5_1 <- rep_5 %>% 
  filter(year == 100) %>% 
  mutate(status = ifelse(f_ratio == 0, "closed", ifelse(b <= 1500, "over", "good"))) %>% 
  mutate(growth = ifelse(r_0 <= .3, "slow", ifelse(r_0 > .3 & r_0 <= .5, "medium", "fast"))) %>% 
  mutate(int = 5)

rep10_1 <- rep_10 %>% 
  filter(year == 100) %>% 
  mutate(status = ifelse(f_ratio == 0, "closed", ifelse(b <= 1500, "over", "good"))) %>% 
  mutate(growth = ifelse(r_0 <= .3, "slow", ifelse(r_0 > .3 & r_0 <= .5, "medium", "fast"))) %>% 
  mutate(int = 10)
  
rep15_1 <- rep_15 %>% 
  filter(year == 100) %>% 
  mutate(status = ifelse(f_ratio == 0, "closed", ifelse(b <= 1500, "over", "good"))) %>% 
  mutate(growth = ifelse(r_0 <= .3, "slow", ifelse(r_0 > .3 & r_0 <= .5, "medium", "fast"))) %>% 
  mutate(int = 15)

rep20_1 <- rep_20 %>% 
  filter(year == 100) %>% 
  mutate(status = ifelse(f_ratio == 0, "closed", ifelse(b <= 1500, "over", "good"))) %>% 
  mutate(growth = ifelse(r_0 <= .3, "slow", ifelse(r_0 > .3 & r_0 <= .5, "medium", "fast"))) %>% 
  mutate(int = 20)

#Define the interval factors:
intervals <- c("Never",20,15,10,5,1) 
intervals_f <- factor(intervals, levels = intervals)

#Combine data sets for starting biomass of 1500:
ai_lowerror <- rbind(rep0_1, rep5_1, rep1_1, rep10_1, rep15_1, rep20_1) %>%
  filter(b_0 == 1500) %>% 
  mutate(assess_int = factor(int, levels = intervals)) %>%
  group_by(assess_int) %>%
  count(status) %>% 
  spread(key = "status", value = "n") %>% 
  mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>% 
  mutate(prop_over = over / (closed + over + good)) %>% 
  mutate(prop_closed = closed / (closed + over + good)) %>% 
  mutate(prop_bad = (closed + over)/ (closed + over + good)) 

#Combine all data sets:
ai_lowerror_all <- rbind(rep0_1, rep20_1, rep15_1, rep10_1, rep5_1, rep1_1) %>%
  mutate(assess_int = factor(int, levels = intervals)) %>%
  group_by(assess_int) %>%
  count(status) %>% 
  spread(key = "status", value = "n") %>% 
  mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>% 
  mutate(prop_bad = (closed + over)/ (closed + over + good)) 

#For a bar graph with the columns by color you need a table that has error, then a variable "type" - over or closed, and then prop
over <- data.frame(assess_int = ai_lowerror$assess_int, type = rep("over",6), prop = ai_lowerror$prop_over)
closed <- data.frame(assess_int = ai_lowerror$assess_int, type = rep("closed",6), prop = ai_lowerror$prop_closed)
graph_df <- rbind(over, closed)

```

Want to show all the runs together and then also break out only the starting biomass of 1500:  
```{r constant-ai-graphs, echo=FALSE}
##Results filter for just 1500 biomass:
ai_graph_1500 <- ggplot(ai_lowerror, aes(x = assess_int, y = prop_bad)) +
  geom_col(position = "dodge", alpha = .7, fill = "#079EDF", width = 0.5)  +
  theme_light()+
  scale_fill_manual(values = c("#079EDF", "#B8CE55"), name = "Failure Type", labels = c("Overfished", "Closed"))+
  coord_cartesian( ylim=c(0,.55), expand = FALSE ) +
  labs(title = "Assessments Intervals", x = "Frequency of Assessment (Years)", y = "Proportion Closed/Overfished")+
  theme(axis.text.x=element_text(size=15), axis.text.y=element_text(size=15), plot.title = element_text(hjust = 0.5, face = "bold", size = 20), axis.title.x = element_text(face = "bold", size = 15), axis.title.y = element_text(face = "bold", size = 15),
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA),legend.background = element_blank(),
    legend.box.background = element_blank()) +
  geom_text(aes(label = round(prop_bad, digits = 2)), position = position_stack(vjust = 0.75), size = 7)

ai_graph_1500
#ggsave(ai_graph_1500, filename = "assessment1.png",  bg = "transparent")


##Stacked columns for 1500 biomass:
ai_graph_stack <- ggplot(graph_df, aes(x= assess_int, y = prop)) +
  geom_col(aes(fill = type), alpha = .7)+
  theme_light()+
  scale_fill_manual(values = c("#079EDF", "#B8CE55"), name = "Failure Type", labels = c("Overfished", "Closed"))+
  coord_cartesian( ylim=c(0,.55), expand = FALSE ) +
  labs(title = "Assessments Intervals", x = "Frequency of Assessment (Years)", y = "Proportion Closed/Overfished")+
  theme(axis.text.x=element_text(size=15), axis.text.y=element_text(size=15), plot.title = element_text(hjust = 0.5, face = "bold", size = 20), axis.title.x = element_text(face = "bold", size = 15), axis.title.y = element_text(face = "bold", size = 15),
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA),legend.background = element_blank(),
    legend.box.background = element_blank())
ai_graph_stack
ggsave(ai_graph_stack, filename = "assessment1.png",  bg = "transparent")
```


##Updating Fmsy:  


```{r setup-updating, include=FALSE, message=FALSE, warning=FALSE}

rep_0u <- read_csv(file=file.path(here(), "/Presentation/objective_2/ai/ai_0rep_lowerror_updatingfmsy.csv"))
rep_1u <- read_csv(file=file.path(here(), "/Presentation/objective_2/ai/ai_rep1_updating.csv"))
rep_5u <- read_csv(file=file.path(here(), "/Presentation/objective_2/ai/ai_5rep_lowerror_updatingfmsy.csv"))
rep_10u <- read_csv(file=file.path(here(), "/Presentation/objective_2/ai/ai_10rep_lowerror_updatingfmsy.csv"))
rep_15u <- read_csv(file=file.path(here(), "/Presentation/objective_2/ai/ai_15rep_lowerror_updatingfmsy.csv"))
rep_20u <- read_csv(file=file.path(here(), "/Presentation/objective_2/ai/ai_20rep_lowerror_updatingfmsy.csv"))

```

Wrangle updating data:  

```{r updating-ai-wrangle, include=FALSE}

rep0_1u <- rep_0u %>% 
  filter(year == 100) %>% 
  mutate(status = ifelse(f_ratio == 0, "closed", ifelse(b <= 1500, "over", "good"))) %>% 
  mutate(growth = ifelse(r_0 <= .3, "slow", ifelse(r_0 > .3 & r_0 <= .5, "medium", "fast"))) %>% 
  mutate(int = "Never") 

rep1_1u <- rep_1u %>% 
  filter(year == 100) %>% 
  mutate(status = ifelse(f_ratio == 0, "closed", ifelse(b <= 1500, "over", "good"))) %>% 
  mutate(growth = ifelse(r_0 <= .3, "slow", ifelse(r_0 > .3 & r_0 <= .5, "medium", "fast"))) %>% 
  mutate(int = 1)

rep5_1u <- rep_5u %>% 
  filter(year == 100) %>% 
  mutate(status = ifelse(f_ratio == 0, "closed", ifelse(b <= 1500, "over", "good"))) %>% 
  mutate(growth = ifelse(r_0 <= .3, "slow", ifelse(r_0 > .3 & r_0 <= .5, "medium", "fast"))) %>% 
  mutate(int = "5")

rep10_1u <- rep_10u %>% 
  filter(year == 100) %>% 
  mutate(status = ifelse(f_ratio == 0, "closed", ifelse(b <= 1500, "over", "good"))) %>% 
  mutate(growth = ifelse(r_0 <= .3, "slow", ifelse(r_0 > .3 & r_0 <= .5, "medium", "fast"))) %>% 
  mutate(int = 10)
  
rep15_1u <- rep_15u %>% 
  filter(year == 100) %>% 
  mutate(status = ifelse(f_ratio == 0, "closed", ifelse(b <= 1500, "over", "good"))) %>% 
  mutate(growth = ifelse(r_0 <= .3, "slow", ifelse(r_0 > .3 & r_0 <= .5, "medium", "fast"))) %>% 
  mutate(int = 15)

rep20_1u <- rep_20u %>% 
  filter(year == 100) %>% 
  mutate(status = ifelse(f_ratio == 0, "closed", ifelse(b <= 1500, "over", "good"))) %>% 
  mutate(growth = ifelse(r_0 <= .3, "slow", ifelse(r_0 > .3 & r_0 <= .5, "medium", "fast"))) %>% 
  mutate(int = 20)


#Define the interval factors:
intervals <- c("Never",20,15,10,5,1) 
intervals_f <- factor(intervals, levels = intervals)

#Combine for starting biomass 1500:

ai_lowerror_u <- rbind(rep0_1u, rep1_1u, rep5_1u, rep10_1u, rep15_1u, rep20_1u) %>%
  filter(b_0 == 1500) %>% 
  mutate(assess_int = factor(int, levels = intervals)) %>%
  group_by(assess_int) %>%
  count(status) %>% 
  spread(key = "status", value = "n") %>% 
  mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>% 
  mutate(prop_bad = (closed + over)/ (closed + over + good))


#Combine for all:
ai_lowerror_all_u <- rbind(rep0_1u, rep1_1u, rep5_1u, rep10_1u, rep15_1u, rep20_1u) %>%
  mutate(assess_int = factor(int, levels = intervals)) %>%
  group_by(assess_int) %>%
  count(status) %>% 
  spread(key = "status", value = "n") %>% 
  mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>% 
  mutate(prop_bad = (closed + over)/ (closed + over + good))



```

Create the graph dataframe:  
```{r wrangle-graph-data, include=FALSE}

##Create the all graph data frame - start with constant and add updating then merge:
graph_c <- data.frame(assessment_interval = ai_lowerror$assess_int, productivity = rep("constant", 6), prop_bad = ai_lowerror_all$prop_bad)
graph_u <- data.frame(assessment_interval = ai_lowerror_u$assess_int, productivity = rep("updating", 6),
                      prop_bad = ai_lowerror_all_u$prop_bad)
graph_both_all <- rbind(graph_c, graph_u)


##Create the 1500 graph data frame - start with constant and updating separately then merge:
graph_c1500 <- data.frame(assessment_interval = ai_lowerror$assess_int, productivity = rep("constant", 6), prop_bad = ai_lowerror$prop_bad)
graph_u1500 <- data.frame(assessment_interval = ai_lowerror$assess_int, productivity = rep("updating", 6), prop_bad = ai_lowerror_u$prop_bad)
graph_both1500 <- rbind(graph_c1500, graph_u1500) 

```



Graphs for both 1500 and all using the constant vs. updating fmsy:  
```{r updating-graphs, echo=FALSE}

ai_1500_both <- ggplot(graph_both1500, aes(x = assessment_interval, y = prop_bad, fill = productivity)) +
  geom_col(position = "dodge", alpha = .7) +
  scale_fill_manual(values = c("#079EDF", "#B8CE55"), name = "Fmsy \n(Productivity)", labels = c("Constant", "Updating"))+
  theme_light()+
  coord_cartesian( ylim=c(0,.55), expand = FALSE ) +
  labs(title = "Assessment Intervals", x = "Frequency of Assessment (Years)", y = "Proportion Closed/Overfished")+
  theme(axis.text.x=element_text(size=15), axis.text.y=element_text(size=15), plot.title = element_text(hjust = 0.5, face = "bold", size = 20), axis.title.x = element_text(face = "bold", size = 15), axis.title.y = element_text(face = "bold", size = 15), legend.title.align=0.5, panel.background = element_rect(fill = "transparent",colour = NA), plot.background = element_rect(fill = "transparent",colour = NA), legend.title=element_text(size=15), 
    legend.text=element_text(size=12),legend.key = element_rect(fill = "transparent", colour = "transparent"), legend.background = element_blank(),
    legend.box.background = element_blank()) 

ai_1500_both
ggsave(ai_1500_both, filename = "assessment2.png",  bg = "transparent")

ai_all_both <- ggplot(graph_both_all, aes(x = assessment_interval, y = prop_bad, fill = productivity)) +
  geom_col(position = "dodge")

ai_all_both
```

