---
title: "hcr_bar_graph"
author: "Chase"
date: "1/22/2020"
output: html_document
---

first, run code in "chase_analysis_jan14.rmd" located in the "Analysis" -> "hcrs_analysis" folder
Copying it here to run:

Run this:
```{r}
library(tidyverse)
library(here)
hcr_rep5c_le <- read_csv(file=file.path(here(),"/Results/hcrs/hcrs_constantfmsy_5rep_lowerror.csv"))
hcr_rep5u_le <- read_csv(file=file.path(here(),"/Results/hcrs/hcrs_updatingfmsy_5rep_lowerror.csv"))
hcr_rep10c_le <- read_csv(file=file.path(here(),"/Results/hcrs/hcrs_constantfmsy_10rep_lowerror.csv"))
hcr_rep10u_le <- read_csv(file=file.path(here(),"/Results/hcrs/hcrs_updatingfmsy_10rep_lowerror.csv"))

rep5c <- hcr_rep5c_le %>% 
  filter(year == 100) %>% 
  mutate(status = ifelse(f_ratio == 0, "closed", ifelse(b <= 1000, "over", "good"))) %>% 
  mutate(growth = ifelse(r_0 <= .3, "slow", ifelse(r_0 > .3 & r_0 <= .5, "medium", "fast")))

rep5u <- hcr_rep5u_le %>% 
  filter(year == 100) %>% 
  mutate(status = ifelse(f_ratio == 0, "closed", ifelse(b <= 1000, "over", "good"))) %>% 
  mutate(growth = ifelse(r_0 <= .3, "slow", ifelse(r_0 > .3 & r_0 <= .5, "medium", "fast")))

rep5u[is.na(rep5u)] <- "misc" #change status=Na to misc


rep10c <- hcr_rep10c_le %>% 
  filter(year == 100) %>% 
  mutate(status = ifelse(f_ratio == 0, "closed", ifelse(b <= 1000, "over", "good"))) %>% 
  mutate(growth = ifelse(r_0 <= .3, "slow", ifelse(r_0 > .3 & r_0 <= .5, "medium", "fast")))
  
rep10u <- hcr_rep10u_le %>% 
  filter(year == 100) %>% 
  mutate(status = ifelse(f_ratio == 0, "closed", ifelse(b <= 1000, "over", "good"))) %>% 
  mutate(growth = ifelse(r_0 <= .3, "slow", ifelse(r_0 > .3 & r_0 <= .5, "medium", "fast")))

rep10u[is.na(rep10u)] <- "misc" #change status=Na to misc

rep5c_c <- rep5c %>%
  group_by(hcr) %>% 
  count(status) %>% 
  spread(key = "status", value = "n") %>%
  mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>% 
  mutate(prop_bad = (over + closed)/(over + good + closed))

rep5u_c <- rep5u %>%
  group_by(hcr) %>% 
  count(status) %>% 
  spread(key = "status", value = "n") %>%
  mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>% 
  mutate(prop_bad = (closed)/(good + closed))

rep10c_c <- rep10c %>%
  group_by(hcr) %>% 
  count(status) %>% 
  spread(key = "status", value = "n") %>%
  mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>% 
  mutate(prop_bad = (over + closed)/(over + good + closed))

rep10u_c <- rep10u %>%
  group_by(hcr) %>% 
  count(status) %>% 
  spread(key = "status", value = "n") %>%
  mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>% 
  mutate(prop_bad = (closed)/(good + closed))


rep_c <- rbind(rep5c, rep10c) %>% 
  group_by(hcr) %>% 
  count(status) %>% 
  spread(key = "status", value = "n") %>% 
  mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>% 
  mutate(prop_closed = closed / (good + closed + over)) %>% 
  mutate(prop_over = over / (good + closed + over)) %>% 
  mutate(prop_bad = (closed + over)/(good + closed + over))

rep_u <- rbind(rep5u, rep10u) %>% 
  group_by(hcr) %>% 
  count(status) %>% 
  spread(key = "status", value = "n") %>% 
  mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>% 
  mutate(simulations = sum(closed + over + good + misc)) %>% 
  mutate(prop_bad = (closed + over)/simulations)

#Create the df for stacked graph:
over_c <- data.frame(hcr = rep_c$hcr, type = rep("over", 10), prop = rep_c$prop_over)
closed_c <- data.frame(hcr = rep_c$hcr, type = rep("closed", 10), prop = rep_c$prop_closed)
rep_c_stacked <- rbind(over_c, closed_c)

```

Dataframe for graphing using the combined dataset:  
```{r}
#Constant FMSY:
alldata <- read_csv(file = file.path(here(), "/Presentation/discussion/alldata_combined.csv"))
alldata[is.na(alldata)] <- "misc" #Change any status = NA to misc for now

prop_all <- alldata %>%
  group_by(hcr, status) %>% 
  count(status) %>% 
  rename("count" = n) %>% 
  spread(key = "status", value = "count") %>% 
  mutate(simulations = sum(closed + good + misc + over)) %>% 
  mutate(prop_over = over / simulations) %>% 
  mutate(prop_closed = closed / simulations) %>% 
  mutate(prop_bad = (closed + over) / simulations)

#Create the df for stacked graph:
over_c <- data.frame(hcr = prop_all$hcr, type = rep("over", 10), prop = prop_all$prop_over)
closed_c <- data.frame(hcr = prop_all$hcr, type = rep("closed", 10), prop = prop_all$prop_closed)
stacked <- rbind(over_c, closed_c)


#Combine constant and updating:
prop_c <- data.frame(hcr = prop_all$hcr, productivity = rep("constant", 10), prop_bad = prop_all$prop_bad)
prop_u <- data.frame(hcr = rep_u$hcr, productivity = rep("updating", 10), prop_bad = rep_u$prop_bad)
stacked <- rbind(prop_c, prop_u)
```




Then this:
```{r}

hcr_bar_10 <- ggplot(rep10c_c, aes(x = hcr, y = prop_bad)) +
  geom_col()

hcr_bar_10

hcr_bar_5 <- ggplot(rep5c_c, aes(x = hcr, y = prop_bad)) +
  geom_col()

hcr_bar_5

hcr_bar_both_c <- ggplot(rep_c, aes(x = hcr, y = prop_bad)) +
  geom_col(fill = "#079EDF",
  position = "dodge",
  alpha = .7) +
  scale_x_reverse(labels=c("0.5" = "50%","0.6" = "40%" ,"0.7" = "30%","0.8" = "20%","0.9" = "10%","1.0" = "0%")) +
  theme_light() +
  coord_cartesian(ylim = c(0, .50), xlim = c(1, 0.45), expand = FALSE) +
  labs(title = "Harvest Control Rule Assessments", x = "Reduction Amount", y = "Proportion Closed/Overfished") +
  theme(
  axis.text.x = element_text(size = 15),
  axis.text.y = element_text(size = 15),
  plot.title = element_text(hjust = 0.5, face = "bold", size = 20),
  axis.title.x = element_text(face = "bold", size = 15),
  axis.title.y = element_text(face = "bold", size = 15),
  legend.title.align = 0.5,
  panel.background = element_rect(fill = "transparent", colour = NA),
  plot.background = element_rect(fill = "transparent", colour = NA),
  legend.title = element_text(size = 15),
  legend.text = element_text(size = 12),
  legend.key = element_rect(fill = "transparent", colour = "transparent"),
  legend.background = element_blank(),
  legend.box.background = element_blank()
  ) +
  geom_text(
  aes(label = round(prop_bad, digits = 2)),
  position = position_dodge(0.9),
  vjust = 2,
  size = 5
  )
  
hcr_bar_both_c

#ggsave(hcr_bar_both_c, filename = "hcr_constant.png",  bg = "transparent")

hcr_bar_u <- ggplot(rep_u, aes(x = hcr, y = prop_bad)) +
  geom_col(aes(fill = hcr)) +
  scale_x_reverse()

hcr_bar_u

rep_u_1 <- rep_u %>% 
  mutate(msy = "updating")

rep_c_1 <- rep_c %>% 
  mutate(msy = "constant")

rep_both <- rbind(rep_u_1, rep_c_1)

hcr_bar_both <- ggplot(stacked, aes(x = hcr, y = prop_bad)) +
  geom_col(aes(fill = productivity), position = "dodge", alpha = .7) +
  scale_fill_manual(
  values = c("#079EDF", "#B8CE55"),
  name = "Fmsy \n(Productivity)",
  labels = c("Constant", "Updating")
  ) +
  theme_light() +
  scale_x_reverse(labels=c("0.5" = "50%","0.6" = "40%" ,"0.7" = "30%","0.8" = "20%","0.9" = "10%","1.0" = "0%")) +
  coord_cartesian(expand = FALSE, xlim = c(1, 0.45), ylim = c(0, 0.55)) +
  labs(title = "Harvest Control Rules", x = "Reduction Amount", y = "Proportion Closed/Overfished") +
  theme(
  axis.text.x = element_text(size = 15),
  axis.text.y = element_text(size = 15),
  plot.title = element_text(hjust = 0.5, face = "bold", size = 20),
  axis.title.x = element_text(face = "bold", size = 15),
  axis.title.y = element_text(face = "bold", size = 15),
  legend.title.align = 0.5,
  panel.background = element_rect(fill = "transparent", colour = NA),
  plot.background = element_rect(fill = "transparent", colour = NA),
  legend.title = element_text(size = 15),
  legend.text = element_text(size = 12),
  legend.key = element_rect(fill = "transparent", colour = "transparent"),
  legend.background = element_blank(),
  legend.box.background = element_blank()
  ) 
  
  hcr_bar_both
#ggsave(hcr_bar_both, filename = "hcr_both_2.3.20.png",  bg = "transparent")
```

New HCR graph showing the proportion overfished vs. closed for constant fmsy:  
```{r stacked-constant-graph}
hcr_stacked_c <- ggplot(stacked, aes(x = hcr, y = prop)) +
  geom_col(aes(fill = type), alpha = .7)+
  theme_light()+
  scale_x_reverse(labels=c("0.5" = "50%","0.6" = "40%" ,"0.7" = "30%","0.8" = "20%","0.9" = "10%","1.0" = "0%")) +
  scale_fill_manual(values = c("#079EDF", "#B8CE55"), name = "Failure Type", labels = c("Overfished", "Closed"))+
  coord_cartesian( ylim=c(0,.50), expand = FALSE ) +
  labs(title = "Harvest Control Rules", x = "Reduction Amount", y = "Proportion Closed/Overfished")+
  theme(axis.text.x=element_text(size=15), axis.text.y=element_text(size=15), plot.title = element_text(hjust = 0.5, face = "bold", size = 20), axis.title.x = element_text(face = "bold", size = 15), axis.title.y = element_text(face = "bold", size = 15),
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA),legend.background = element_blank(),
    legend.box.background = element_blank())


hcr_stacked_c
#ggsave(hcr_stacked_c, filename = "hcr_stack_2.3.20.png",  bg = "transparent")






```

Severe climate graph:  
```{r}
#Severe climate graph for appendix:
alldata <- read_csv(file = file.path(here(), "/Presentation/discussion/alldata_combined.csv"))

prop_sev <- alldata %>%
  filter(r_s < -0.00767) %>% 
  group_by(hcr, status) %>% 
  count(status) %>% 
  rename("count" = n) %>% 
  spread(key = "status", value = "count") %>% 
  mutate(simulations = sum(closed + good + over)) %>% 
  mutate(prop_over = over / simulations) %>% 
  mutate(prop_closed = closed / simulations) %>% 
  mutate(prop_bad = (closed + over) / simulations)

#Create the df for stacked graph:
over_sev <- data.frame(hcr = prop_sev$hcr, type = rep("over", 10), prop = prop_sev$prop_over)
closed_sev <- data.frame(hcr = prop_sev$hcr, type = rep("closed", 10), prop = prop_sev$prop_closed)
stacked_sev <- rbind(over_sev, closed_sev)

#Graph:
hcr_stacked_sev <- ggplot(stacked_sev, aes(x = hcr, y = prop)) +
  geom_col(aes(fill = type), alpha = .7)+
  theme_light()+
  scale_x_reverse(labels=c("0.5" = "50%","0.6" = "40%" ,"0.7" = "30%","0.8" = "20%","0.9" = "10%","1.0" = "0%")) +
  scale_fill_manual(values = c("#079EDF", "#B8CE55"), name = "Failure Type", labels = c("Overfished", "Closed"))+
  coord_cartesian( ylim=c(0,.90), expand = FALSE ) +
  labs(title = "Harvest Control Rules", x = "Reduction Amount", y = "Proportion Closed/Overfished")+
  theme(axis.text.x=element_text(size=15), axis.text.y=element_text(size=15), plot.title = element_text(hjust = 0.5, face = "bold", size = 20), axis.title.x = element_text(face = "bold", size = 15), axis.title.y = element_text(face = "bold", size = 15),
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA),legend.background = element_blank(),
    legend.box.background = element_blank())


hcr_stacked_sev
ggsave(hcr_stacked_sev, filename = "hcr_stack_2.3.20.png",  bg = "transparent")
```

