---
title: "discussion_graph"
output: html_document
---

#{.tabset}

##Setup

```{r include = FALSE, warning=FALSE, message = FALSE}
library(tidyverse)

alldata <- read_csv("alldata.csv")

```


##Data Wrangling

After exploration we are highlighting the following scenarios:  

Initial conditions:  
climate = Moderate (-0.00767 - 0)  
Assessment = 10 years  

Combinations:  

1. Error = 0.5 and HCR = 0.5  
2. Error = 0.3 and HCR = 0.8  
3. Error = 0.1 and HCR = 0.95  


```{r include = FALSE}
#Create the baseline conditions df:
baseline <- alldata %>% 
  filter(r_s < 0) %>% 
  filter(r_s >= -0.00767) %>% 
  filter(year == 100) %>% 
  filter(assess == "10")


#Scenario 1
scen1 <- baseline %>% 
  filter(error == 0.5) %>% 
  filter(hcr == 0.5) %>% 
  group_by(error, hcr) %>% 
  count(status) %>% 
  spread(key = "status", value = "n") %>% 
  mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>% 
  mutate(prop_bad = (closed)/(good + closed)) %>% 
  mutate(prop_closed = (closed)/(good + closed)) %>% 
  mutate(prop_over = 0)

#Scenario 2
scen2 <- baseline %>% 
  filter(error == 0.3) %>% 
  filter(hcr == 0.8) %>% 
  group_by(error, hcr) %>% 
  count(status) %>% 
  spread(key = "status", value = "n") %>% 
  mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>% 
  mutate(prop_bad = (closed + over)/(good + over + closed)) %>% 
  mutate(prop_closed = (closed)/(good + over + closed)) %>% 
  mutate(prop_over = over / (good + over + closed))

#Scenario 3
scen3 <- baseline %>% 
  filter(error == 0.1) %>% 
  filter(hcr == 0.95) %>% 
  group_by(error, hcr) %>% 
  count(status) %>% 
  spread(key = "status", value = "n") %>% 
  mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>% 
  mutate(prop_bad = (closed + over)/(good + over + closed)) %>% 
  mutate(prop_closed = (closed)/(good + over + closed)) %>% 
  mutate(prop_over = over / (good + over + closed))


#Create the graphing data frame:
scenario <- c("1", "2", "3")
prop_bad <- c(scen1$prop_bad, scen2$prop_bad, scen3$prop_bad)
type <- c("over", "closed", "over", "closed", "over", "closed")
prop <- c(scen1$prop_over, scen1$prop_closed, scen2$prop_over, scen2$prop_closed, scen3$prop_over, scen3$prop_closed)

scen_combined <- data.frame(scenario = scenario, prop_bad = prop_bad)
scen_stacked <- data.frame(scenario = c("1", "1", "2", "2", "3", "3"), type = type, prop = prop)

```


##Graphs:

Graph just the prop_bad for each scenario: 
```{r echo=FALSE}

scen_graph <- ggplot(scen_combined, aes(x = scenario, y = prop_bad)) + 
  geom_col(aes(fill = type), alpha = 0.7, width = .6, fill = "#079EDF")+
  theme_light()+
  coord_cartesian( ylim=c(0,.25), expand = FALSE ) +
  labs(title = "General Trade-Offs", x = "Scenario", y = "Proportion of Failures")+
  scale_x_discrete(labels=c("1" = "Error: 50% \nHCR: 50%", "2" = "Error: 30% \nHCR: 20%","3" = "Error: 10% \nHCR: 5%")) +
  theme(axis.text.x=element_text(size=15), axis.text.y=element_text(size=15), plot.title = element_text(hjust = 0.5, face = "bold", size = 20), axis.title.x = element_text(face = "bold", size = 15, vjust = -.5), axis.title.y = element_text(face = "bold", size = 15), legend.title.align=0.5, panel.background = element_rect(fill = "transparent",colour = NA), plot.background = element_rect(fill = "transparent",colour = NA), legend.title=element_text(size=15), 
    legend.text=element_text(size=12),legend.key = element_rect(fill = "transparent", colour = "transparent"), legend.background = element_blank(),
    legend.box.background = element_blank()) 

scen_graph
ggsave(scen_graph, filename = "scen.png",  bg = "transparent")
```

Graph stacked by over/closed proportions:  
```{r echo = FALSE}

scen_stack_graph <- ggplot(scen_stacked, aes(x = scenario, y = prop, fill = type)) +
  geom_col(aes(fill = type), alpha = 0.7, width = .6)+
  scale_fill_manual(values = c("#079EDF", "#B8CE55"), name = "Failure Type", labels = c("Closed", "Overfished")) +
  theme_light()+
  coord_cartesian( ylim=c(0,.25), expand = FALSE ) +
  labs(title = "General Trade-Offs", x = "Scenario", y = "Proportion of Failures")+
  scale_x_discrete(labels=c("1" = "Error: 50% \nHCR: 50%", "2" = "Error: 30% \nHCR: 20%","3" = "Error: 10% \nHCR: 5%")) +
  theme(axis.text.x=element_text(size=15), axis.text.y=element_text(size=15), plot.title = element_text(hjust = 0.5, face = "bold", size = 20), axis.title.x = element_text(face = "bold", size = 15, vjust = -.5), axis.title.y = element_text(face = "bold", size = 15), legend.title.align=0.5, panel.background = element_rect(fill = "transparent",colour = NA), plot.background = element_rect(fill = "transparent",colour = NA), legend.title=element_text(size=15), 
    legend.text=element_text(size=12),legend.key = element_rect(fill = "transparent", colour = "transparent"), legend.background = element_blank(),
    legend.box.background = element_blank()) 

scen_stack_graph

ggsave(scen_stack_graph, filename = "scen_stack.png",  bg = "transparent")

```

